import type { TechnicalItemFamily } from '../../lib/interview/types';

export const numericEvFamily: TechnicalItemFamily = {
  id: '10000000-0000-4000-8000-000000000001',
  slug: 'basic-ev-bridge-numeric',
  primaryConceptId: 'E02',
  secondaryConceptIds: ['E01'],
  prerequisiteConceptIds: ['E01'],
  learningObjectives: ['Bridge equity value to enterprise value with consistent signs.'],
  topic: 'enterprise_value',
  difficulty: 'foundation',
  cognitiveOperation: 'calculate',
  variantCoverage: ['standard', 'reversed', 'numerical', 'assumption_changed', 'applied_company', 'explain_simply', 'followup_chain'],
  questionVersion: {
    version: 1,
    promptTemplate: 'A company has equity value of {{EQUITY}}, debt of {{DEBT}} and cash of {{CASH}}. What is enterprise value?',
    followupPromptTemplates: [],
    jurisdiction: 'GLOBAL_IFRS',
    currency: 'AUD',
    effectiveFrom: '2026-08-02T00:00:00.000Z',
    effectiveTo: null,
    interviewRounds: ['first_round'],
    interviewerLevels: ['analyst', 'associate'],
    calculatorPolicy: 'mental_math',
    expectedAnswerDurationSeconds: { minimum: 15, target: 30, maximum: 60 },
    assumptions: [],
  },
  parameterSpec: {
    seedVersion: 1,
    parameters: [
      { code: 'EQUITY', type: 'currency', minimum: '100', maximum: '500', step: '25', unit: 'A$m' },
      { code: 'DEBT', type: 'currency', minimum: '10', maximum: '150', step: '10', unit: 'A$m' },
      { code: 'CASH', type: 'currency', minimum: '5', maximum: '100', step: '5', unit: 'A$m' },
    ],
    derivedValues: [{ code: 'EV', expression: 'EQUITY + DEBT - CASH', precision: 0, rounding: 'half_up' }],
    constraints: [{ code: 'EV_POSITIVE', expression: 'EV > 0', errorMessage: 'EV must be positive' }],
    transformationRules: [
      { variant: 'reversed', promptTemplate: 'Enterprise value is {{EV}}, debt is {{DEBT}}, and cash is {{CASH}}. What is equity value?' },
      { variant: 'numerical', promptTemplate: 'Calculate EV from equity {{EQUITY}}, debt {{DEBT}}, and cash {{CASH}}.' },
      { variant: 'assumption_changed', promptTemplate: 'If cash is {{CASH}}, explain and calculate EV from equity {{EQUITY}} and debt {{DEBT}}.' },
      { variant: 'applied_company', promptTemplate: 'Mapped Co reports equity value {{EQUITY}}, borrowings {{DEBT}}, and cash {{CASH}}. Estimate EV.' },
      { variant: 'explain_simply', promptTemplate: 'Explain to a new analyst why {{DEBT}} is added and {{CASH}} is subtracted from {{EQUITY}}.' },
      { variant: 'followup_chain', promptTemplate: 'Start with EV for equity {{EQUITY}}, debt {{DEBT}}, cash {{CASH}}, then defend each bridge sign.' },
    ],
  },
  rubricVersion: {
    version: 1,
    answerOutline: ['Enterprise value equals equity value plus debt minus cash.', 'The generated answer is {{EV}}.'],
    mustHitPoints: [
      { code: 'FORMULA', description: 'States the correct bridge.', weight: 0.5, evidenceRules: [{ kind: 'semantic', value: 'equity plus debt minus cash', negated: false }] },
      { code: 'ANSWER', description: 'Calculates the resolved EV.', weight: 0.5, evidenceRules: [{ kind: 'numeric', value: 'EV', negated: false }] },
    ],
    bonusPoints: [],
    fatalErrors: [{ misconceptionCode: 'E02.BRIDGE_SIGN_ERROR', description: 'Reverses debt or cash.', triggerRules: [{ kind: 'sign', value: 'DEBT_OR_CASH', negated: false }], blocksMastery: true }],
    acceptedVariants: [],
    commonMisconceptions: [{ misconceptionCode: 'E02.BRIDGE_SIGN_ERROR', explanation: 'Financing claims and excess cash use opposite bridge signs.', remediationId: 'e02-bridge-sign' }],
    deterministicChecks: [{ code: 'EV', expression: 'EQUITY + DEBT - CASH', expectedUnit: 'A$m', absoluteTolerance: '1', relativeTolerance: '0.01', requiredSign: 'positive', acceptedRounding: [0, 1] }],
    followupTree: [{ nodeId: 'signs', parentNodeId: null, trigger: 'partial', questionTemplate: 'Why do debt and cash have opposite signs?', expectedPoints: ['Debt is a financing claim; cash is a non-operating asset.'], maximumDepth: 1 }],
  },
  sources: [{
    sourceId: '20000000-0000-4000-8000-000000000001',
    sourceType: 'independent_bank_style',
    title: 'Independently authored EV bridge teaching brief',
    publisher: 'MappedLabs',
    url: null,
    documentDate: '2026-08-02',
    accessedAt: '2026-08-02T00:00:00.000Z',
    pageOrSection: null,
    jurisdiction: 'GLOBAL_IFRS',
    rightsBasis: 'fact_reference_only',
    verbatimTextUsed: false,
    candidateConsentRecorded: false,
    confidentialMaterialAttestedAbsent: false,
  }],
  bankReliability: { classification: 'not_applicable', bankName: null, independentReportCount: 0, recruitingCycleCount: 0, lastReportDate: null },
  review: {
    authorId: '30000000-0000-4000-8000-000000000001',
    technicalReviewerId: '30000000-0000-4000-8000-000000000002',
    realismReviewerId: '30000000-0000-4000-8000-000000000003',
    approverId: '30000000-0000-4000-8000-000000000004',
    authoredAt: '2026-08-02T00:00:00.000Z',
    approvedAt: '2026-08-02T00:00:00.000Z',
    nextReviewAt: '2027-08-02T00:00:00.000Z',
    changeReason: 'Test fixture',
    founderOverride: false,
    founderOverrideReason: null,
  },
};
