/**
 * MappedLabs wordmark — the selected identity (concept A, "Plotted M").
 *
 * Inline SVG rather than an <img> so each concept can recolour the mark to its
 * own ink and accent without shipping a variant file per direction. The
 * letterform paths are Archivo SemiBold outlines generated by
 * scripts/build-brand-assets.mjs — do not hand-edit them; regenerate instead.
 * Standalone SVG/PNG exports live in web/public/brand/.
 */
interface Props {
  className?: string;
  /** Colour of the traverse and the lettering. */
  ink?: string;
  /** Colour of the station node. Pass the same value as `ink` for one-colour use. */
  accent?: string;
  /** Render the symbol only, without the lettering. */
  symbolOnly?: boolean;
  /** Include the measurement datum. Drop it below ~32px, where it turns to noise. */
  datum?: boolean;
  title?: string;
}

import { WORDMARK_PATH, WORDMARK_WIDTH, WORDMARK_CAP } from '@/lib/lab/wordmark-path';

export function Wordmark({
  className = '',
  ink = 'currentColor',
  accent = '#C8452A',
  symbolOnly = false,
  datum = true,
  title = 'MappedLabs',
}: Props) {
  const symbol = (
    <>
      {datum && (
        <>
          <path d="M2.5 39 H61.5" stroke={ink} strokeWidth="1.5" opacity="0.28" />
          <path d="M3.25 35.5 v7 M60.75 35.5 v7" stroke={ink} strokeWidth="1.5" opacity="0.28" />
        </>
      )}
      <path
        d="M9 55 L9 9 L32 39 L55 9 L55 55"
        fill="none"
        stroke={ink}
        strokeWidth="8.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle cx="32" cy="39" r="4.75" fill={accent} />
    </>
  );

  if (symbolOnly) {
    return (
      <svg viewBox="0 0 64 64" className={className} role="img" aria-label={title}>
        {symbol}
      </svg>
    );
  }

  /* Lockup: the symbol's drawn field (54.5 of its 64 box) is scaled a little
     taller than the cap height, then optically centred on the cap band. */
  const FIELD = 54.5;
  const scale = (WORDMARK_CAP * 1.34) / FIELD;
  const symBox = 64 * scale;
  const gap = 15;
  const baseline = symBox / 2 + WORDMARK_CAP / 2;
  const total = symBox + gap + WORDMARK_WIDTH;

  return (
    <svg
      viewBox={`0 0 ${total.toFixed(2)} ${symBox.toFixed(2)}`}
      className={className}
      role="img"
      aria-label={title}
    >
      <g transform={`scale(${scale.toFixed(4)})`}>{symbol}</g>
      <g transform={`translate(${(symBox + gap).toFixed(2)} ${baseline.toFixed(2)})`}>
        <path d={WORDMARK_PATH} fill={ink} />
      </g>
    </svg>
  );
}
